name: Update the version

on:
  workflow_dispatch:
  schedule:
    - cron: '39 0/6 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - run: nix-shell update.sh
        id: update
      - if: ${{ steps.update.outputs.changed }}
        uses: tibdex/github-app-token@36464acb844fc53b9b8b2401da68844f6b05ebb0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - if: ${{ steps.update.outputs.changed }}
        name: Create Pull Request
        uses: peter-evans/create-pull-request@d9d6fd980e1e0904e8e4dce3f0992640091bde37
        with:
          title: "Update package to ${{ steps.update.outputs.version }}"
          body: ''
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
          base: main
